---
- hosts: all
  become: true
  tasks:
    - name: Remove Apache
      ansible.builtin.apt:
        name: apache2
        state: absent
        purge: yes
        autoremove: yes
        update_cache: yes

