---
- hosts: wordpress
  become: true
  tasks:
    - name: Pull MySQL image
      community.docker.docker_image:
        name: mysql
        tag: "5.7"
        source: pull

    - name: Run MySQL container
      community.docker.docker_container:
        name: wordpress-db
        image: mysql:5.7
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: example_root_password
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress_user
          MYSQL_PASSWORD: wordpress_password
        ports:
          - "3306:3306"
        volumes:
          - wordpress-db-data:/var/lib/mysql

    - name: Pull WordPress image
      community.docker.docker_image:
        name: wordpress
        source: pull

    - name: Run WordPress container
      community.docker.docker_container:
        name: wordpress
        image: wordpress
        state: started
        restart_policy: always
        env:
          WORDPRESS_DB_HOST: localhost:3306
          WORDPRESS_DB_USER: wordpress_user
          WORDPRESS_DB_PASSWORD: wordpress_password
          WORDPRESS_DB_NAME: wordpress
        ports:
          - "8080:80"
        volumes:
          - wordpress-data:/var/www/html

volumes:
  wordpress-db-data:
  wordpress-data:
