---
- hosts: laravel
  gather_facts: false
  collections:
    - community.docker
  tasks:
    - name: List docker networks
      community.docker.docker_network_info:
        name: laravel-net
      register: result

    - debug:
        var: result
